User interface
kilonzi/TicTacToe pull request #2
Opened 2019-10-29 21:00 UTC by edemagbenyo

User interface implementation:
Contains game flow
Takes input from users and return game output

2019-10-31 13:38 UTC, mcrd25 requested changes
# Changes Required 🤓 

Hi @edemagbenyo and @kilonzi 👋,

I hope you guys are well! 🙂 
This milestone is good so far! However, there are a couple of things needed to change.

### Required Changes
Currently, not everything works (of course! And that's fine for this milestone, however, you do need to consider displaying board after each move which I've noticed you forgot to address.

Please muck this behavior (whether through code or inline comments so that we know that this behavior has been considered moving unto the next milestone. 🙏 🙂  

### OPTIONAL CHANGES (not necessary)
- Address optional comments

*Everything else looks good so far!*


***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2019-10-31 13:38 UTC, mcrd25 commented on bin/main.rb
> +    case game_status
[OPTIONAL]
consider setting this `game_status` to something even at random for each move so that you'd know the case statements work. 🙂 

so could set game status to `win`, `draw` or `incomplete` etc but for this milestone, it's fine if you don't it would also prevent the error that shows when you try to enter a number from 1 to 9 in the console.

2019-10-31 13:38 UTC, mcrd25 commented on bin/main.rb
> +puts "EMPTY BOARD"
I see that you print empty board but do not print board after each move (please address this 🙏)

2019-10-31 15:29 UTC, edemagbenyo commented
Thanks @mcrd25  for your comment and suggestions. We will address the issues your raised immediately and submit another pull request for review.

2019-10-31 23:29 UTC, maelfosso requested changes
# Changes required

Hello @kilonzi @edemagbenyo 

Thank you for the improvement :+1: 
However there are still some changes to do. 

There is that error when running the game
```ruby
$ bin/main.rb 
bin/main.rb:34: warning: integer literal in conditional range
Welcome to the TIC-TAC TOE GAME. 
Rules of the game: 
1.Each player has only move at a time. 
2. A player can put only assigned symbol. 
HOW TO WIN: 
The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row is the winner.
Please enter the name of the first player:
1
1, you have been assigned X
Please enter the name of the second player:
Mael
Mael, you have been assigned O
PRINT BOARD
Press Enter to start game
1 Enter your move, any number within 1-9 and press Enter. 
Enter 'q' or 'quit' to quit game. Enter r to Restart the game
Elvis
You made an invalid choice.
1 Enter your move, any number within 1-9 and press Enter. 
Enter 'q' or 'quit' to quit game. Enter r to Restart the game
1
1, your choice is 1
Traceback (most recent call last):
bin/main.rb:37:in `<main>': undefined local variable or method `game_status' for main:Object (NameError)
```
- Please compare that list and add the missing points in your mock :
[x] Tells which player turn it is
[x] Asks player to select from available moves
[ ] Informs player if selected move is invalid
[ ] Displays board after player move
[x] Informs player if selected move is a winning move
[x] Informs player if selected move is a draw move
[x] Repeats all actions for next player's move


Kindly make the changes and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-10-31 23:29 UTC, maelfosso commented on bin/main.rb
> +while true
I think you also have to change that line according to @mcrd25  recommandation

2019-11-02 12:29 UTC, samgaco requested changes
HI @edemagbenyo and @kilonzi :high_brightness: 

- [x] The mock is giving an error when giving it a valid move (a number between 1-9)


- [x] The loop is still a bit unclear. 


Please see the comments below and work on these changes before submitting them back for another code review.

Regards

--------------------------
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-11-02 12:29 UTC, samgaco commented on bin/main.rb
> +  if (1..9).include?(choice.to_i)
we are getting some problems over here:

```
1.Each player has only move at a time. 
2. A player can put only assigned symbol. 
HOW TO WIN: 
The player who succeeds in placing three of their marks in a horizontal, vertical, or diagonal row is the winner.
Please enter the name of the first player:
mike
mike, you have been assigned X
Please enter the name of the second player:
john
john, you have been assigned O
PRINT BOARD
Press Enter to start game
mike Enter your move, any number within 1-9 and press Enter. 
Enter 'q' or 'quit' to quit game. Enter r to Restart the game
8
mike, your choice is 8
Traceback (most recent call last):
bin/main.rb:38:in `<main>': uninitialized constant Game (NameError)
```

2019-11-02 12:29 UTC, samgaco commented on bin/main.rb
> +while true
true should be inside a variable so when we find a resolution for a match (win or draw) we can switch that variable to `false` , for example:

```
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

2019-11-04 05:02 UTC, whiz25 requested changes
## Hey team, good job so far :+1: 
Your game still has bugs in it. Please make sure you understand what a reviewer is asking so you don't spend so much time on one PR.
I could approve this PR since it's reached the max number of cycles for a review but there is still a lot you need to do in this milestone and given that other milestones build on top of this, we really need to complete all requirements for this milestone before moving forward.
![Screenshot from 2019-11-04 07-56-44](https://user-images.githubusercontent.com/19773024/68100510-6194a280-fed9-11e9-8846-72e1c65fdedb.png)

2019-11-04 05:03 UTC, whiz25 reviewed
Don't forget to fix the conflicts in the files.

2019-11-11 17:59 UTC, kilonzi commented
@whiz25 We have resolved the issues

2019-11-11 19:49 UTC, wathigo approved these changes
## Approved  :smile: 

### Great work implementing the suggested changes. 
**You may move on :next_track_button:** 

_Happy Coding :smile:  
Approved by: **Simon Wathigo**_

2019-11-13 23:03 UTC, closed without merging