Game logic
kilonzi/TicTacToe pull request #3
Opened 2019-11-01 19:34 UTC by edemagbenyo

Implement game logic using various classes such as:
Game
Board
Player
Move

2019-11-02 18:32 UTC, whiz25 commented on bin/main.rb
> +#Display winner and name or draw
remove these comments.

2019-11-02 18:32 UTC, whiz25 commented on bin/main.rb
> +  # get input
remove all comments from your code.

2019-11-02 18:34 UTC, whiz25 commented on lib/move.rb
> +      choice = gets.chomp
this should be implemented in the ```main.rb``` file.

2019-11-02 18:35 UTC, whiz25 commented on lib/board.rb
> +    puts " #{@arr[6]} | #{@arr[7]} | #{@arr[8]} "
this file should not have any ```puts, print``` but instead ```return``` statements.

2019-11-02 18:39 UTC, whiz25 requested changes
## Good job 👍 
You guys have met all the minimum requirements for this milestone. I am happy for you.
However, we need to fix a few things before we can merge this PR.
- [x] look at my comments carefully and implement the requested changes.

#### Make the requested changes and re-submit for another review.

### Martin Afani

2019-11-02 19:44 UTC, edemagbenyo commented
Thanks Martin. We will implement the requested changes and submit another review.

2019-11-03 18:05 UTC, whiz25 approved these changes
You have implemented the requested changes and it's, therefore, a :+1: from me. Go ahead and merge.
### Martin Afani

2019-11-03 19:31 UTC, merged